# Generated by Django 4.0.3 on 2022-03-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flavour',
            field=models.CharField(default='', max_length=40),
        ),
    ]
