# Generated by Django 4.0.3 on 2022-03-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_flavour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flavour',
            field=models.CharField(choices=[('FOUR_CHEESE', 'fourCheese'), ('MUSHROOMS', 'mushrooms'), ('PEPPER_AND_ONIONS', 'peppers_and_onions'), ('CHICKEN_CUTLET', 'ChickenCutlet'), ('ITALIAN_SAUSAGE', 'ItalianSausage'), ('PEPPERONI', 'Pepperoni')], max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('SMALL', 'small'), ('MEDIUM', 'medium'), ('LARGE', 'large'), ('EXTRA_LARGE', 'extraLarge')], max_length=20),
        ),
    ]
